development:
  adapter: postgresql
  encoding: unicode
  database: mina_development
  pool: 5
  username: ghanshyam
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: mina_test
  pool: 5
  username: ghanshyam
  password:
